(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=ba(this);function u(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var k=a[d];if(!(k in c))break a;c=c[k]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(l||"")+"_"+k++,l)}function c(l,f){this.g=l;p(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",k=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=r[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function v(a){return a.raw=a}function w(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},x;
if("function"==typeof Object.setPrototypeOf)x=Object.setPrototypeOf;else{var y;a:{var ea={a:!0},fa={};try{fa.__proto__=ea;y=fa.a;break a}catch(a){}y=!1}x=y?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=x;
function z(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.V=b.prototype}function ia(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.A=!1;var e=this.j();try{f(e.resolve,e.reject)}catch(g){e.reject(g)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(e){e(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var e=this;this.i(function(){e.s()})}this.g.push(f)};var k=r.setTimeout;c.prototype.i=function(f){k(f,0)};c.prototype.s=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var e=0;e<f.length;++e){var g=
f[e];f[e]=null;try{g()}catch(h){this.j(h)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(h){return function(m){g||(g=!0,h.call(e,m))}}var e=this,g=!1;return{resolve:f(this.K),reject:f(this.s)}};b.prototype.K=function(f){if(f===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.M(f);else{a:switch(typeof f){case "object":var e=null!=f;break a;case "function":e=!0;break a;default:e=!1}e?this.J(f):this.v(f)}};
b.prototype.J=function(f){var e=void 0;try{e=f.then}catch(g){this.s(g);return}"function"==typeof e?this.N(e,f):this.v(f)};b.prototype.s=function(f){this.I(2,f)};b.prototype.v=function(f){this.I(1,f)};b.prototype.I=function(f,e){if(0!=this.h)throw Error("Cannot settle("+f+", "+e+"): Promise already settled in state"+this.h);this.h=f;this.i=e;2===this.h&&this.L();this.S()};b.prototype.L=function(){var f=this;k(function(){if(f.T()){var e=r.console;"undefined"!==typeof e&&e.error(f.i)}},1)};b.prototype.T=
function(){if(this.A)return!1;var f=r.CustomEvent,e=r.Event,g=r.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof e?f=new e("unhandledrejection",{cancelable:!0}):(f=r.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return g(f)};b.prototype.S=function(){if(null!=this.g){for(var f=0;f<this.g.length;++f)l.h(this.g[f]);this.g=null}};var l=new c;b.prototype.M=
function(f){var e=this.j();f.B(e.resolve,e.reject)};b.prototype.N=function(f,e){var g=this.j();try{f.call(e,g.resolve,g.reject)}catch(h){g.reject(h)}};b.prototype.then=function(f,e){function g(n,t){return"function"==typeof n?function(S){try{h(n(S))}catch(T){m(T)}}:t}var h,m,q=new b(function(n,t){h=n;m=t});this.B(g(f,h),g(e,m));return q};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.B=function(f,e){function g(){switch(h.h){case 1:f(h.i);break;case 2:e(h.i);break;default:throw Error("Unexpected state: "+
h.h);}}var h=this;null==this.g?l.h(g):this.g.push(g);this.A=!0};b.resolve=d;b.reject=function(f){return new b(function(e,g){g(f)})};b.race=function(f){return new b(function(e,g){for(var h=w(f),m=h.next();!m.done;m=h.next())d(m.value).B(e,g)})};b.all=function(f){var e=w(f),g=e.next();return g.done?d([]):new b(function(h,m){function q(S){return function(T){n[S]=T;t--;0==t&&h(n)}}var n=[],t=0;do n.push(void 0),t++,d(g.value).B(q(n.length-1),m),g=e.next();while(!g.done)})};return b});
function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
u("WeakMap",function(a){function b(g){this.g=(e+=Math.random()+1).toString();if(g){g=w(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(g){var h=typeof g;return"object"===h&&null!==g||"function"===h}function k(g){if(!A(g,f)){var h=new c;p(g,f,{value:h})}}function l(g){var h=Object[g];h&&(Object[g]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&k(m);return h(m)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),
m=new a([[g,2],[h,3]]);if(2!=m.get(g)||3!=m.get(h))return!1;m.delete(g);m.set(h,4);return!m.has(g)&&4==m.get(h)}catch(q){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var e=0;b.prototype.set=function(g,h){if(!d(g))throw Error("Invalid WeakMap key");k(g);if(!A(g,f))throw Error("WeakMap key fail: "+g);g[f][this.g]=h;return this};b.prototype.get=function(g){return d(g)&&A(g,f)?g[f][this.g]:void 0};b.prototype.has=function(g){return d(g)&&A(g,
f)&&A(g[f],this.g)};b.prototype.delete=function(g){return d(g)&&A(g,f)&&A(g[f],this.g)?delete g[f][this.g]:!1};return b});
u("Map",function(a){function b(){var e={};return e.o=e.next=e.head=e}function c(e,g){var h=e.g;return ca(function(){if(h){for(;h.head!=e.g;)h=h.o;for(;h.next!=h.head;)return h=h.next,{done:!1,value:g(h)};h=null}return{done:!0,value:void 0}})}function d(e,g){var h=g&&typeof g;"object"==h||"function"==h?l.has(g)?h=l.get(g):(h=""+ ++f,l.set(g,h)):h="p_"+g;var m=e.h[h];if(m&&A(e.h,h))for(e=0;e<m.length;e++){var q=m[e];if(g!==g&&q.key!==q.key||g===q.key)return{id:h,list:m,index:e,l:q}}return{id:h,list:m,
index:-1,l:void 0}}function k(e){this.h={};this.g=b();this.size=0;if(e){e=w(e);for(var g;!(g=e.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),g=new a(w([[e,"s"]]));if("s"!=g.get(e)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var h=g.entries(),m=h.next();if(m.done||m.value[0]!=e||"s"!=m.value[1])return!1;m=h.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!h.next().done?!1:!0}catch(q){return!1}}())return a;var l=new WeakMap;k.prototype.set=function(e,g){e=0===e?0:e;var h=d(this,e);h.list||(h.list=this.h[h.id]=[]);h.l?h.l.value=g:(h.l={next:this.g,o:this.g.o,head:this.g,key:e,value:g},h.list.push(h.l),this.g.o.next=h.l,this.g.o=h.l,this.size++);return this};k.prototype.delete=function(e){e=d(this,e);return e.l&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.h[e.id],e.l.o.next=e.l.next,e.l.next.o=e.l.o,e.l.head=null,this.size--,
!0):!1};k.prototype.clear=function(){this.h={};this.g=this.g.o=b();this.size=0};k.prototype.has=function(e){return!!d(this,e).l};k.prototype.get=function(e){return(e=d(this,e).l)&&e.value};k.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};k.prototype.keys=function(){return c(this,function(e){return e.key})};k.prototype.values=function(){return c(this,function(e){return e.value})};k.prototype.forEach=function(e,g){for(var h=this.entries(),m;!(m=h.next()).done;)m=m.value,
e.call(g,m[1],m[0],this)};k.prototype[Symbol.iterator]=k.prototype.entries;var f=0;return k});var B=this||self;function C(a){return a};var ja=Promise;function ka(a){this.h=a}ka.prototype.g=function(a,b,c){this.h.then(function(d){d.g(a,b,c)})};function la(a){this.data=a};function ma(a){this.h=a}ma.prototype.g=function(a,b,c){c=void 0===c?[]:c;var d=new MessageChannel;na(d.port1,b);this.h.postMessage(a,[d.port2].concat(c))};function oa(a,b){na(a,b);return new ma(a)}function na(a,b){b&&(a.onmessage=function(c){b(new la(c.data,oa(c.ports[0])))})};function pa(a){var b=a.F,c=void 0===a.u?"ZNWN1d":a.u,d=void 0===a.onMessage?void 0:a.onMessage,k=void 0===a.D?void 0:a.D;return qa({destination:a.destination,O:function(){return b.contentWindow},P:ra(a.origin),u:c,onMessage:d,D:k})}
function qa(a){var b=a.destination,c=a.O,d=a.P,k=void 0===a.R?void 0:a.R,l=a.u,f=void 0===a.onMessage?void 0:a.onMessage,e=void 0===a.D?void 0:a.D,g=Object.create(null);d.forEach(function(h){g[h]=!0});return new ka(new ja(function(h,m){function q(n){if(n.source===c())if(!0!==g[n.origin]){b.removeEventListener("message",q,!1);var t=d.join(", ");m(Error("Origin mismatch while establishing channel. Expected "+(1===d.length?t:"one of ["+t+"]")+", but received "+n.origin+"."))}else(n.data.n||n.data)===
l&&(b.removeEventListener("message",q,!1),k&&n.data.t!==k?m(Error("Token mismatch while establishing channel. Expected "+k+", but received "+n.data.t+".")):(h(oa(n.ports[0],f)),e&&e(n)))}b.addEventListener("message",q,!1)}))}function ra(a){a="string"===typeof a?[a]:a;var b=Object.create(null);a.forEach(function(c){if("null"===c)throw Error("Receiving from null origin not allowed without token verification. Please use NullOriginConnector.");b[c]=!0});return a};var sa={},D=null;var ta="undefined"!==typeof Uint8Array;var E="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function ua(a,b){Object.isFrozen(a)||(E?a[E]|=b:void 0!==a.C?a.C|=b:Object.defineProperties(a,{C:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function va(a){var b;E?b=a[E]:b=a.C;return null==b?0:b}function F(a){ua(a,1);return a}function wa(a){return Array.isArray(a)?!!(va(a)&2):!1};function xa(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var G,ya=Object.freeze(F([]));function H(a){if(wa(a.m))throw Error("Cannot mutate an immutable Message");}var za="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function Aa(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function Ba(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&ta&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!D){D={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],k=0;5>k;k++){var l=c.concat(d[k].split(""));sa[k]=l;for(var f=0;f<l.length;f++){var e=l[f];void 0===D[e]&&(D[e]=f)}}}b=sa[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(k=l=0;l<a.length-2;l+=
3){var g=a[l],h=a[l+1];e=a[l+2];f=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|e>>6];e=b[e&63];c[k++]=f+g+h+e}f=0;e=d;switch(a.length-l){case 2:f=a[l+1],e=b[(f&15)<<2]||d;case 1:a=a[l],c[k]=b[a>>2]+b[(a&3)<<4|f>>4]+e+d}return c.join("")}}return a};function Ca(a){var b=Da;b=void 0===b?Ea:b;return Fa(a,b)}function Ga(a,b){if(null!=a){if(Array.isArray(a))a=Fa(a,b);else if(xa(a)){var c={},d;for(d in a)c[d]=Ga(a[d],b);a=c}else a=b(a);return a}}function Fa(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=Ga(c[d],b);Array.isArray(a)&&va(a)&1&&F(c);return c}function Da(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=Ba(a);return Array.isArray(a)?Ca(a):a}function Ea(a){return ta&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};function I(a,b,c){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:(void 0===c?0:c)&&a.h&&(c=a.h[b],null!=c)?c:a.m[b+a.i]}function J(a,b,c,d,k){d=void 0===d?!1:d;(void 0===k?0:k)||H(a);b<a.j&&!d?a.m[b+a.i]=c:(a.h||(a.h=a.m[a.j+a.i]={}))[b]=c}function K(a,b){for(var c=0,d=0;d<b.length;d++){var k=b[d];null!=I(a,k)&&(0!==c&&J(a,c,void 0,!1,!0),c=k)}return c}function Ha(a,b,c){H(a);a.g||(a.g={});var d=null!=c?c.m:c;a.g[1]=c;H(a);(b=K(a,b))&&1!==b&&null!=d&&(a.g&&b in a.g&&(a.g[b]=void 0),J(a,b));J(a,1,d)};function L(a,b,c){a||(a=M);M=null;var d=this.constructor.h;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.g||0);this.g=void 0;this.m=a;a:{d=this.m.length;a=d-1;if(d&&(d=this.m[a],xa(d))){this.j=a-this.i;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.i),this.h=void 0):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.j)a+=this.i,(d=this.m[a])?Array.isArray(d)&&F(d):this.m[a]=ya;else{d=this.h||(this.h=this.m[this.j+this.i]={});var k=d[a];k?Array.isArray(k)&&F(k):
d[a]=ya}}L.prototype.toJSON=function(){var a=this.m;return G?a:Ca(a)};function Ia(a){G=!0;try{return JSON.stringify(a.toJSON(),Ja)}finally{G=!1}}function N(a,b){if(null==b||""==b)return new a;b=JSON.parse(b);if(!Array.isArray(b))throw a=typeof b,Error("Expected to deserialize an Array but got "+("object"!=a?a:b?Array.isArray(b)?"array":a:"null")+": "+b);M=b;a=new a(b);M=null;return a}L.prototype.toString=function(){return this.m.toString()};function Ja(a,b){return Ba(b)}var M;function O(){L.apply(this,arguments)}z(O,L);if(za){var Ka={};Object.defineProperties(O,(Ka[Symbol.hasInstance]=Aa(function(){throw Error("Cannot perform instanceof checks for MutableMessage");}),Ka))};function P(){O.apply(this,arguments)}z(P,O);if(za){var La={};Object.defineProperties(P,(La[Symbol.hasInstance]=Aa(Object[Symbol.hasInstance]),La))};function Q(a,b){if(!b(a))throw Error(String(a));};function Ma(a){return"string"===typeof a}function R(a){return"function"===typeof a};var U;function V(a,b){this.g=b===Na?a:""}V.prototype.i=!0;V.prototype.h=function(){return this.g.toString()};V.prototype.toString=function(){return this.g+""};function Oa(a){return a instanceof V&&a.constructor===V?a.g:"type_error:TrustedResourceUrl"}var Na={};function W(a,b){this.g=b===Pa?a:""}W.prototype.i=!0;W.prototype.h=function(){return this.g.toString()};W.prototype.toString=function(){return this.g.toString()};var Qa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Pa={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Ra={};function Sa(){}function X(a){this.g=a}z(X,Sa);X.prototype.toString=function(){return this.g.toString()};function Ta(a){if(void 0===U){var b=null;var c=B.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:C,createScript:C,createScriptURL:C})}catch(d){B.console&&B.console.error(d.message)}U=b}else U=b}b=U;b=null==b?void 0:b.createScriptURL(a);return new X(null!=b?b:a,Ra)}function Ua(a){if(a instanceof X)return a.g;throw Error("");}
function Va(a){a=Ua(a);var b="undefined"!==typeof window?window.trustedTypes:void 0;b=null!=b?b:null;return(null==b?0:b.isScriptURL(a))?TrustedScriptURL.prototype.toString.apply(a):a};function Wa(a){var b=ia.apply(1,arguments);if(0===b.length)return Ta(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return Ta(c.join(""))}function Xa(a,b){var c=Va(a);if(/#/.test(c))throw Error("");var d=/\?/.test(c)?"&":"?";b.forEach(function(k,l){k=k instanceof Array?k:[k];for(var f=0;f<k.length;f++){var e=k[f];null!==e&&void 0!==e&&(c+=d+encodeURIComponent(l)+"="+encodeURIComponent(String(e)),d="&")}});return Ta(c)};function Ya(a){return!!a&&"function"===typeof a.openConsoleTab&&"function"===typeof a.attachOverlay};function Za(a){P.call(this,a)}z(Za,P);function $a(a){P.call(this,a)}z($a,P);function ab(a){P.call(this,a)}z(ab,P);var bb=[1];function cb(a){P.call(this,a)}z(cb,P);function db(a){P.call(this,a)}z(db,P);var eb=[1];function fb(a){P.call(this,a)}z(fb,P);var gb=[1];function hb(a){P.call(this,a)}z(hb,P);function ib(a){return a instanceof Element}function jb(){var a=kb.h;this.h=kb.g;this.g=a}jb.prototype.openConsoleTab=function(a,b,c){Q(a,Ma);Q(b,R);Q(c,R);a=N(cb,a);var d=new MessageChannel,k=d.port1;d=d.port2;k.onmessage=function(l){"ACK"===l.data?c(k):b(l.data)};this.h.openConsoleTab(a,d)};
jb.prototype.attachOverlay=function(a,b,c,d){Q(a,Ma);Q(b,ib);Q(c,R);Q(d,R);a=N(Za,a);var k=new MessageChannel,l=k.port1;k=k.port2;l.onmessage=function(f){"ACK"===f.data?d(l):c(f.data)};this.g.attachOverlay(a,b,k)};var lb=window.URL,Y=B.document.baseURI||B.window.location.href||"",mb;try{new lb("http://example.com"),mb=!0}catch(a){mb=!1}var nb=mb;
function Z(a){var b=document;var c="A";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c);try{var d=new W(a,Pa);if(d instanceof W)var k=d;else d instanceof W?k=d:(d="object"==typeof d&&d.i?d.h():String(d),Qa.test(d)||(d="about:invalid#zClosurez"),k=new W(d,Pa));var l=k;c.href=l instanceof W&&l.constructor===W?l.g:"type_error:SafeUrl";var f=c.protocol}catch(e){throw Error(a+" is not a valid URL.");}if(""===f||":"===f||":"!=f[f.length-1])throw Error(a+" is not a valid URL.");
if(!ob.has(f))throw Error(a+" is not a valid URL.");if(!c.hostname)throw Error(a+" is not a valid URL.");a={href:c.href,protocol:c.protocol,username:"",password:"",hostname:c.hostname,pathname:"/"+c.pathname,search:c.search,hash:c.hash};ob.get(c.protocol)===c.port?(a.host=a.hostname,a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=c.host,a.port=c.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a}
function pb(a){try{var b=new lb(a)}catch(d){throw Error(a+" is not a valid URL.");}var c=ob.get(b.protocol);if(!c)throw Error(a+" is not a valid URL.");if(!b.hostname)throw Error(a+" is not a valid URL.");if("null"!=b.origin)return b;a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash};a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port;return a}
function qb(a){if(nb){if(!Y)return pb(a);var b=pb(Y);try{return pb(a)}catch(k){}return new lb(a,b.href)}if(!Y)return Z(a);b=Z(Y);try{return Z(a)}catch(k){}var c=b.username,d=b.password;c=b.protocol+"//"+(c&&d?c+":"+d+"@":c?c+"@":d?":"+d+"@":"")+b.host;d=a[0];"/"===d||"\\"===d?a=c+a:"?"===d?a=c+b.pathname+a:d&&"#"!==d?(d=b.pathname.lastIndexOf("/"),a=c+(0<d?b.pathname.substring(0,d):"")+"/"+a):a=c+b.pathname+b.search+a;return Z(a)}
var ob=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]);function rb(){this.g=sb;this.h=0}
rb.prototype.attachOverlay=function(a,b,c,d){var k=this.h++,l=document.createElement("div");l.id="gatc:overlay:div:"+k;l.classList.add("gatc:overlay:div");l.style.position="absolute";l.style.top="0";l.style.left="0";l.style.bottom="0";l.style.right="0";l.style.border="none";b.appendChild(l);var f=document.createElement("iframe");f.id="gatc:overlay:frame:"+k;f.classList.add("gatc:overlay:frame");f.style.width="100%";f.style.height="100%";f.style.border="none";b=pa({destination:window,F:f,origin:qb(this.g.G.toString()).origin,
u:"gatc:overlay:channel:"+k,onMessage:function(e){e.data&&(e=N(hb,e.data.data||""),console.log("Received overlay message: ",e.toString(),k))}});d&&d(f);d=Xa(this.g.G,new Map([["origin",window.origin],["index",k.toString()]]));f.src=d instanceof Sa?Ua(d).toString():Oa(d).toString();l.appendChild(f);l=new fb;Ha(l,gb,a);a={data:Ia(l),ports:[c]};b.g(a,void 0,a.ports)};function tb(){var a=sb;var b=void 0===b?document.body:b;this.s=a;this.v=b;this.j=!1}tb.prototype.install=function(a){if(this.j)throw Error("Panel manager may only be installed once.");this.j=!0;ub(this,a)};tb.prototype.openConsoleTab=function(a,b){if(!this.j)throw Error("Panel manager must be installed before access.");var c=new db;Ha(c,eb,a);a={data:Ia(c),ports:[b]};this.A.g(a,void 0,a.ports)};
function ub(a,b){if(document.getElementById("gatc:panel:div")||document.getElementById("gatc:panel:frame")||document.getElementById("gatc:panel:scrollshim"))throw Error("Panel elements already present in document.");a.g=document.createElement("div");a.g.id="gatc:panel:div";a.g.style.position="fixed";a.g.style.bottom="0";a.g.style.left="0";a.g.style.right="0";a.g.style.height="330px";a.g.style.borderTop="1px solid #ccc";a.g.style.background="white";a.g.style.overflow="hidden";a.g.style.zIndex="2147483646";
a.g.style.display="none";a.v.appendChild(a.g);a.h=document.createElement("div");a.h.id="gatc:panel:scrollshim";a.h.style.width="100%";a.h.style.height="330px";a.h.style.clear="both";a.h.style.display="none";a.v.appendChild(a.h);a.i=document.createElement("iframe");a.i.id="gatc:panel:frame";a.i.style.width="100%";a.i.style.height="100%";b&&b(a.i);a.A=pa({destination:window,F:a.i,origin:qb(a.s.H.toString()).origin,u:"gatc:panel:channel",onMessage:function(c){if(c.data&&(c=N(ab,c.data.data||""),1===
K(c,bb))){var d=1===K(c,bb)?1:-1;if(-1===d)c=null;else{c.g||(c.g={});var k=c.g[d];if(k)c=k;else{var l=I(c,d,!1);if(null==l)c=k;else{k=new $a(l);if(wa(c.m)){l=k.m;if(!Array.isArray(l))throw Error("cannot mark non-array as immutable");ua(l,2)}c=c.g[d]=k}}}if(!a.g)throw Error("Panel manager must be installed before access.");c=I(c,1);switch(null==c?0:c){case 1:vb(a,"none");break;case 2:vb(a,"")}}}});a.A.g(null,function(){});b=Xa(a.s.H,new Map([["origin",window.origin]]));a.i.src=b instanceof Sa?Ua(b).toString():
Oa(b).toString();a.g.appendChild(a.i)}function vb(a,b){a.g&&(a.g.style.display=b);a.h&&(a.h.style.display=b)};var wb=v(["https://www.googletagservices.com/console/host/host.js"]),xb=v(["https://www.googletagservices.com/console/panel/index.html"]),yb=v(["https://www.googletagservices.com/console/overlay/index.html"]),sb={U:Wa(wb),H:Wa(xb),G:Wa(yb)};var kb=new function(){var a=new rb;this.g=new tb;this.h=a};if(Ya(window.gatc_host))throw Error("Host module already installed on window.");kb.g.install();var zb=new jb;Q(zb,Ya);if(Array.isArray(window.gatc_host))for(var Ab=w(window.gatc_host),Bb=Ab.next();!Bb.done;Bb=Ab.next()){var Cb=Bb.value;"function"===typeof Cb&&Cb(zb)}window.gatc_host=zb;}).call(this);
